# global:
#   runner: 
#     containers:
#     - image: razorci/golang:1.14
#       environment:
#       - DB_CONNECTION=mongodb://appuser:apppass@localhost:27017/test
#       - DB_NAME=test
#     - image: bitnami/mongodb:4.4.1
#       environment:
#       - MONGODB_ROOT_PASSWORD=adminpass
#       - MONGODB_DATABASE=test
#       - MONGODB_USERNAME=appuser
#       - MONGODB_PASSWORD=apppass
tasks:
  build-backend:
    steps:
    - checkout
    - docker/build:
        image: saurabh3460/web
        push: true
        tags: ["${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}", "latest"]
        dockerfile: django/Dockerfile
        context: django/
    - workspace/persist:
        paths: [bin]

  build-frontend:
    steps:
    - workspace/attach
    - commands:
    - |
        ls 
    - docker/build:
        image: saurabh3460/ui
        push: true
        tags: ["${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}", "latest"]
        dockerfile: angular/Dockerfile
        context: angular/

#   deploy:
#     depends: [build-backend, build-frontend]
#     variables:
#     - ARGOCD_SERVER=argocd.codecrux.com
#     - APP_NAME=transpora-transpora
#     - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
#     - ARGOCD_VERSION=v2.5.9
#     steps:
#     - commands:
#       - |
#         export CONTAINER_NAME=web-app # change as per yout app
#         export IMAGE=acme/web-app:v1 # change as per your app
#         ssh root@example.com <<'ENDSSH'
#         docker pull $IMAGE
#         docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME
#         docker run --name=$CONTAINER_NAME --restart=always -v $PWD:/app -d $IMAGE
#         ENDSSH

# trigger:
#   when: branch == "release-dev"

