tasks:
  build-backend:
    steps:
    # - checkout
    # - docker/build:
    #     image: saurabh3460/web
    #     push: true
    #     tags: ["${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}", "latest"]
    #     dockerfile: django/Dockerfile
    #     context: django/
    - commands:
      - |
          # cp docker-compose.yaml angular
          cat ~/.docker/config.json
    - workspace/persist:
        paths: [angular]


  build-frontend:
    depends: [build-backend]
    steps:
    - workspace/attach
    - commands:
      - |
          ls
    - docker/build:
        image: saurabh3460/ui
        push: true
        tags: ["${CI_COMMIT_SHA:0:8}", "latest"]
        dockerfile: angular/Dockerfile
        context: angular

  deploy:
    depends: [build-backend, build-frontend]
    variables:
    - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
    steps:
    - workspace/attach
    - run: |
        ls angular
        ssh ubuntu@43.204.22.232 <<'ENDSSH'
        cd angular
        docker-compose pull
        docker-compose up
        ENDSSH

# trigger:
#   when: branch == "release-dev"

