tasks:
  build-backend:
    steps:
    - checkout
    - docker/build:
        image: saurabh3460/web
        push: true
        tags: ["${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}", "latest"]
        dockerfile: django/Dockerfile
        context: django/
    - workspace/persist:
        paths: [angular, docker-compose.yaml]

  build-frontend:
    depends: [build-backend]
    steps:
    - workspace/attach
    - docker/build:
        image: saurabh3460/ui
        push: true
        tags: ["${CI_COMMIT_SHA:0:8}", "latest"]
        dockerfile: angular/Dockerfile
        context: angular

  deploy:
    depends: [build-backend, build-frontend]
    steps:
    - workspace/attach
    - run: |
        cat ~/.ssh/config
        scp docker-compose.yaml ubuntu@cloud-native.me:docker-compose.yaml
        ssh -v ubuntu@cloud-native.me <<'ENDSSH'
          docker-compose pull
          docker-compose down
          docker-compose up -d
        ENDSSH


