version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  dj:
    container_name: dj
    image: saurabh3460/web
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS=dev
      - DB_NAME_DJANGO=postgres
      - DB_USER_DJANGO=postgres
      - DB_PASSWORD_DJANGO=postgres
      - CLOUD_SQL_INSTANCE_IP=db
  ng:
    container_name: ng
    image: saurabh3460/ui
    ports:
      - "8080:80"
